FROM mcr.Microsoft.com/dotnet/sdk:8.0 as build
WORKDIR /app
EXPOSE 80

# copy all .csproj files and restore distinct layers. Use of the same COPY command
# for every dockerfile inthe project to take advantage of docker caching
COPY MicroservicesBasedOn.Net_NextJS_React.sln MicroservicesBasedOn.Net_NextJS_React.sln
COPY src/AuctionService/AuctionService.csproj src/AuctionService/AuctionService.csproj
COPY src/SearchService/SearchService.csproj src/SearchService/SearchService.csproj
COPY src/Contracts/Contracts.csproj src/Contracts/Contracts.csproj
COPY src/IdentityService/IdentityService.csproj src/IdentityService/IdentityService.csproj
COPY src/GatewayService/GatewayService.csproj src/GatewayService/GatewayService.csproj
COPY src/BiddingService/BiddingService.csproj src/BiddingService/BiddingService.csproj

# Restore packege deps
RUN dotnet restore MicroservicesBasedOn.Net_NextJS_React.sln

# Copy the app folder over
COPY src/IdentityService src/IdentityService
# Add dependencies for the project if they are

WORKDIR /app/src/IdentityService
RUN dotnet publish -c Release -o /app/src/out

# Build runtime image
FROM mcr.Microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/src/out .
ENTRYPOINT ["dotnet", "IdentityService.dll"]